# Generated by Django 4.2.2 on 2023-06-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('iId', models.AutoField(primary_key=True, serialize=False)),
                ('iType', models.CharField(max_length=30)),
                ('iMoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iRemark', models.CharField(max_length=55)),
                ('iTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('pType', models.CharField(max_length=30)),
                ('pMoney', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pRemark', models.CharField(max_length=55)),
                ('pTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=30, unique=True)),
                ('usex', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254)),
                ('utel', models.BigIntegerField()),
            ],
        ),
    ]
